spring:
  datasource:
    url: jdbc:postgresql://db.joytsesydvoenrfrjopd.supabase.co:5432/postgres
    username: postgres
    password: gmAaW3pkwSdalE82
  jpa:
    hibernate:
      ddl-auto: validate
flyway:
  enabled: true
  validate-on-migrate: true