spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 2
  jpa:
    hibernate:
      ddl-auto: validate
flyway:
  enabled: true
  validate-on-migrate: true