CREATE TABLE T_SERVICE
(
    CODE        VARCHAR(128) PRIMARY KEY,
    NAME        VARCHAR(128) NOT NULL,
    PRICE       DECIMAL (10,2) NOT NULL,
    CREATED_AT  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT  TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
