CREATE TABLE APPOINTMENT
(
    ID              UUID PRIMARY KEY,
    CLIENT_EMAIL    VARCHAR(128) NOT NULL,
    START_AT        TIMESTAMP NOT NULL,
    CREATED_AT      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT      TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_appointment_start_at ON APPOINTMENT (START_AT);