CREATE TABLE APPOINTMENT_SERVICE (
    APPOINTMENT_ID  UUID NOT NULL,
    SERVICE_CODE    VARCHAR(128) NOT NULL,
    PRIMARY KEY     (APPOINTMENT_ID, SERVICE_CODE),
    FOREIGN KEY     (APPOINTMENT_ID) REFERENCES APPOINTMENT(ID) ON DELETE CASCADE,
    FOREIGN KEY     (SERVICE_CODE) REFERENCES T_SERVICE(CODE)
);

CREATE INDEX idx_appointment_service_appointment ON APPOINTMENT_SERVICE (APPOINTMENT_ID);
CREATE INDEX idx_appointment_service_code ON APPOINTMENT_SERVICE (SERVICE_CODE);
