CREATE TABLE T_BUSINESS_HOURS (
    WEEKDAY         INTEGER PRIMARY KEY CHECK (weekday BETWEEN 1 AND 7),
    START_TIME      TIME NOT NULL,
    END_TIME        TIME NOT NULL,
    CREATED_AT      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT      TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
