CREATE TABLE T_BUSINESS_HOURS_EXCEPTIONS (
    EXCEPTION_DAY   DATE PRIMARY KEY,
    START_TIME      TIME,
    END_TIME        TIME,
    IS_CLOSED       BOOLEAN NOT NULL DEFAULT FALSE,
    CREATED_AT      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT      TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
