CREATE TABLE T_BARBER (
    ID              UUID PRIMARY KEY,
    ACCESS_TOKEN    VARCHAR(2048),
    REFRESH_TOKEN   VARCHAR(2048),
    TOKEN_EXPIRY    TIMESTAMP NOT NULL,
    IS_CONNECTED    BOOLEAN NOT NULL DEFAULT FALSE,
    CREATED_AT      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT      TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
