DO $$
DECLARE
    REGULAR_START_TIME TIME := '09:00';
    REGULAR_END_TIME TIME := '19:30';
BEGIN
    FOR i IN 1..5 LOOP
        INSERT INTO T_BUSINESS_HOURS (WEEKDAY, START_TIME, END_TIME)
        VALUES (i, REGULAR_START_TIME, REGULAR_END_TIME)
        ON CONFLICT (WEEKDAY) DO NOTHING;
    END LOOP;

    INSERT INTO T_BUSINESS_HOURS (WEEKDAY, START_TIME, END_TIME)
    VALUES (6, REGULAR_START_TIME, '20:30')
    ON CONFLICT (WEEKDAY) DO NOTHING;

    INSERT INTO T_BUSINESS_HOURS (WEEKDAY, START_TIME, END_TIME)
    VALUES (7, REGULAR_START_TIME, '20:30')
    ON CONFLICT (WEEKDAY) DO NOTHING;
END $$;
