DO $$
BEGIN
    INSERT INTO T_BUSINESS_HOURS_EXCEPTIONS (EXCEPTION_DAY, START_TIME, END_TIME, IS_CLOSED)
    VALUES ('2025-12-24', '09:00', '12:00', FALSE)
    ON CONFLICT (EXCEPTION_DAY) DO NOTHING;

    INSERT INTO T_BUSINESS_HOURS_EXCEPTIONS (EXCEPTION_DAY, START_TIME, END_TIME, IS_CLOSED)
    VALUES ('2025-12-25', NULL, NULL, TRUE)
    ON CONFLICT (EXCEPTION_DAY) DO NOTHING;

    INSERT INTO T_BUSINESS_HOURS_EXCEPTIONS (EXCEPTION_DAY, START_TIME, END_TIME, IS_CLOSED)
    VALUES ('2025-12-31', '09:00', '14:00', FALSE)
    ON CONFLICT (EXCEPTION_DAY) DO NOTHING;

    INSERT INTO T_BUSINESS_HOURS_EXCEPTIONS (EXCEPTION_DAY, START_TIME, END_TIME, IS_CLOSED)
    VALUES ('2026-01-01', NULL, NULL, TRUE)
    ON CONFLICT (EXCEPTION_DAY) DO NOTHING;
END $$;
