INSERT INTO T_SERVICE (CODE, NAME, PRICE, SLOT_TIME)
VALUES ('HC', 'Hair Cut', 14.00, 40)
ON CONFLICT (CODE) DO NOTHING;

INSERT INTO T_SERVICE (CODE, NAME, PRICE, SLOT_TIME)
VALUES ('BT', 'Beard Trimming', 5.00, 20)
ON CONFLICT (CODE) DO NOTHING;

INSERT INTO T_SERVICE (CODE, NAME, PRICE, SLOT_TIME)
VALUES ('HT', 'Hair Treatment', 9.00, 20)
ON CONFLICT (CODE) DO NOTHING;

COMMIT;