INSERT INTO T_SERVICE (CODE, NAME, PRICE)
VALUES ('HC', 'Hair Cut', 14.00)
ON CONFLICT (CODE) DO NOTHING;

INSERT INTO T_SERVICE (CODE, NAME, PRICE)
VALUES ('BT', 'Beard Trimming', 5.00)
ON CONFLICT (CODE) DO NOTHING;

INSERT INTO T_SERVICE (CODE, NAME, PRICE)
VALUES ('HT', 'Hair Treatment', 9.00)
ON CONFLICT (CODE) DO NOTHING;

COMMIT;