INSERT INTO T_BUSINESS_HOURS (WEEKDAY, START_TIME, END_TIME)
VALUES (1, '09:00', '19:30')
ON CONFLICT (WEEKDAY) DO NOTHING;

INSERT INTO T_BUSINESS_HOURS (WEEKDAY, START_TIME, END_TIME)
VALUES (2, '09:00', '19:30')
ON CONFLICT (WEEKDAY) DO NOTHING;

INSERT INTO T_BUSINESS_HOURS (WEEKDAY, START_TIME, END_TIME)
VALUES (3, '09:00', '19:30')
ON CONFLICT (WEEKDAY) DO NOTHING;

INSERT INTO T_BUSINESS_HOURS (WEEKDAY, START_TIME, END_TIME)
VALUES (4, '09:00', '19:30')
ON CONFLICT (WEEKDAY) DO NOTHING;

INSERT INTO T_BUSINESS_HOURS (WEEKDAY, START_TIME, END_TIME)
VALUES (5, '09:00', '19:30')
ON CONFLICT (WEEKDAY) DO NOTHING;

INSERT INTO T_BUSINESS_HOURS (WEEKDAY, START_TIME, END_TIME)
VALUES (6, '09:00', '20:30')
ON CONFLICT (WEEKDAY) DO NOTHING;

INSERT INTO T_BUSINESS_HOURS (WEEKDAY, START_TIME, END_TIME)
VALUES (7, '09:00', '20:30')
ON CONFLICT (WEEKDAY) DO NOTHING;

COMMIT;

INSERT INTO T_BUSINESS_HOURS_EXCEPTIONS (EXCEPTION_DAY, START_TIME, END_TIME, IS_CLOSED)
VALUES ('2025-12-24', '09:00', '12:00', FALSE)
ON CONFLICT (EXCEPTION_DAY) DO NOTHING;

INSERT INTO T_BUSINESS_HOURS_EXCEPTIONS (EXCEPTION_DAY, START_TIME, END_TIME, IS_CLOSED)
VALUES ('2025-12-25', NULL, NULL, TRUE)
ON CONFLICT (EXCEPTION_DAY) DO NOTHING;

INSERT INTO T_BUSINESS_HOURS_EXCEPTIONS (EXCEPTION_DAY, START_TIME, END_TIME, IS_CLOSED)
VALUES ('2025-12-31', '09:00', '14:00', FALSE)
ON CONFLICT (EXCEPTION_DAY) DO NOTHING;

INSERT INTO T_BUSINESS_HOURS_EXCEPTIONS (EXCEPTION_DAY, START_TIME, END_TIME, IS_CLOSED)
VALUES ('2026-01-01', NULL, NULL, TRUE)
ON CONFLICT (EXCEPTION_DAY) DO NOTHING;

COMMIT;
